# Generated by Django 2.2.1 on 2019-07-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20190514_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dogum_tarihi',
            new_name='birth_day',
        ),
    ]
