# Generated by Django 2.2.1 on 2019-05-05 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kaydetmek için başlık giriniz:', max_length=100, null=True, verbose_name='Başlık giriniz: ')),
                ('content', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Etkinlik Açıklaması')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='yazi', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Gönderiler',
                'verbose_name_plural': 'Gönderi',
            },
        ),
    ]
