# Generated by Django 2.2.1 on 2019-05-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190508_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subscriber',
        ),
    ]
