# Generated by Django 2.2.1 on 2019-05-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='finished_date',
            new_name='starter_date',
        ),
    ]
