# Generated by Django 2.2.1 on 2019-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190513_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventMemberCount',
            field=models.IntegerField(default=0, verbose_name='Üye Sayısı'),
        ),
    ]
