# Generated by Django 2.2.1 on 2019-05-13 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_event_eventmembercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventMemberCount',
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=True, related_name='event_member', to='events.Event')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='event_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorilere Eklenen Gönderileri',
            },
        ),
    ]
