# Generated by Django 2.2.1 on 2019-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190513_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmember',
            options={'verbose_name_plural': 'Etkinliğe gelen katılımcılar'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
