# Generated by Django 2.2.1 on 2019-05-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190514_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='12', editable=False, null=True, unique=True),
        ),
    ]
