# Generated by Django 2.2.1 on 2019-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190515_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('diğer', 'DİĞER'), ('yazılım', 'YAZILIM'), ('grafik tasarım', 'GRAFIK TASARIM')], max_length=53, null=True, verbose_name='Kategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='size',
            field=models.IntegerField(default=0, null=True, verbose_name='Katılımcı sayısı'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
