# Generated by Django 2.2.1 on 2019-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190515_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
