# Generated by Django 2.2.1 on 2019-05-19 20:20

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventmember_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default/marijuana.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=events.models.upload_to, verbose_name='Resim'),
        ),
    ]
