# Generated by Django 2.2.1 on 2019-05-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finish_date',
        ),
    ]
