# Generated by Django 2.2.1 on 2019-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20190611_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starter_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç günü'),
        ),
    ]
