# Generated by Django 2.2.1 on 2019-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20190629_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='starter_date',
        ),
        migrations.AddField(
            model_name='event',
            name='dogum_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
