# Generated by Django 2.2.1 on 2019-06-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20190629_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dogum_tarihi',
        ),
        migrations.AddField(
            model_name='event',
            name='starter_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç günü'),
        ),
    ]
