# Generated by Django 2.2.1 on 2019-06-29 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0027_auto_20190629_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=True, related_name='favorite_event', to='events.Event')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='favorite_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorilere Eklenen Event',
            },
        ),
    ]
