# Generated by Django 2.2.1 on 2019-06-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_favoriteevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
