# Generated by Django 2.2.1 on 2019-06-30 19:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_remove_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
