<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-07-05 21:12
=======
# Generated by Django 2.2.1 on 2019-07-05 15:31
>>>>>>> c0e0fd0ac13c6cfc690e12aaf3a4c74fbdb5ed04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20190630_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
    ]
