# Generated by Django 2.2.1 on 2019-07-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20190705_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Adres'),
        ),
    ]
